In [1]:
import torch
x = torch.FloatTensor([[1,2],[3,4]]).requires_grad_(True)


requires_grad_(True) : 이 텐서에 대해서 미분값을 구한다 (일반적인 함수에서는 사용안함. 기울기 분석용)

In [2]:
x1 = x + 2
x2 = x - 2
x3 = x1 * x2
y = x3.sum()
print(x1)
print(x2)
print(x3)
print(y)

tensor([[3., 4.],
        [5., 6.]], grad_fn=<AddBackward0>)
tensor([[-1.,  0.],
        [ 1.,  2.]], grad_fn=<SubBackward0>)
tensor([[-3.,  0.],
        [ 5., 12.]], grad_fn=<MulBackward0>)
tensor(14., grad_fn=<SumBackward0>)


In [ ]:
y.backward() # y값을 기준으로 연결된 모든 텐서의 기울기를 자동으로 계산

In [5]:
print(x.grad) # y에 대해 계산된 x의 기울기(∂y/∂x)

tensor([[2., 4.],
        [6., 8.]])


y = (x + 2) (x - 2) -> y = ∑(x^2 -4)  
∂/∂x(-4) = 0  
=> -4는 미분 결과에 영향을 주지 않음  

제곱항은
$\frac{\partial}{\partial x_i}(x_i^2) = 2x_i$

각 원소에 대해서
$\frac{\partial y}{\partial x_i} = 2x_i$

벡터 형태로 보면
$\frac{\partial y}{\partial x} = 2x$

결론적으로 x.grad 결과는 2x 형태로 나오게 된다.

In [7]:
print(x) # 텐서 값은 변경 없음. 역전파는 기울기를 계산만하고, 수정하지 않음.

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)


In [ ]:
x3.detach_().numpy() # x3를 계산 그래프에서 분리(autograd 추적 제거)하고 numpy 배열로 반환

array([[-3.,  0.],
       [ 5., 12.]], dtype=float32)

detach() : 복사본을 만들면서 분리(권장)  
detach_() : 원본 자체를 분리 (detach() + inplace 옵션)

In [ ]:
x2 # 추적중 확인

tensor([[-1.,  0.],
        [ 1.,  2.]], grad_fn=<SubBackward0>)

In [ ]:
x3 # numpy 배열 형태로 출력

tensor([[-3.,  0.],
        [ 5., 12.]])