In [2]:
import torch
import numpy as np

1. 행렬 곱셈

In [3]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

print(x.size(), y.size())

torch.Size([2, 2]) torch.Size([2, 2])


In [4]:
z = torch.matmul(x, y)  # 행렬곱 연산
z.size()

torch.Size([2, 2])

In [5]:
z = x @ y
z.size()

torch.Size([2, 2])

In [7]:

x = torch.FloatTensor([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]],[[13,14],[15,16],[17,18]]]) # (3,3,2)
y = torch.FloatTensor([[[1,2,2],[1,2,2]],[[1,3,3],[1,3,3]],[[1,4,4],[1,4,4]]]) # (3,2,3)

print(x.size(), y.size())

torch.Size([3, 3, 2]) torch.Size([3, 2, 3])


In [8]:
z = x @ y
z.size()

torch.Size([3, 3, 3])

In [10]:
# torch.bmm(x,y): 각 배치별로 x[i] @ y[i]를 수행
torch.bmm(x,y)

tensor([[[  3.,   6.,   6.],
         [  7.,  14.,  14.],
         [ 11.,  22.,  22.]],

        [[ 15.,  45.,  45.],
         [ 19.,  57.,  57.],
         [ 23.,  69.,  69.]],

        [[ 27., 108., 108.],
         [ 31., 124., 124.],
         [ 35., 140., 140.]]])

|구분|matmul(@)|bmm|
|---|---|---|
|입력차원|1D ~ ND|3D만 허용|
|batch 처리|자동 해석 + 브로드캐스팅 가능|batch 크기 동일 필수|
|연산 범위|범용 행렬곱|배치 행렬곱|
|유연성|높음|낮음|

2. 신경망 내 내적 연산으로 보는 선형 변환
- W.T 전치를 이용해 입력 차원과 곱셈이 가능해지도록 맞춰준다.

In [14]:
x = torch.FloatTensor([[1,2,3]]) # (1,3)
W = torch.FloatTensor([[0.1,0.2,0.3],[0.4,0.5,0.6]]) # (2,3)

print(x.size(), W.size())
print(x,"\n",y)

torch.Size([1, 3]) torch.Size([2, 3])
tensor([[1., 2., 3.]]) 
 tensor([[1.4000, 3.2000]])


In [16]:
y = torch.matmul(x, W.T) # (1,3) @ (3,2)
print(y.size())
print(y)

torch.Size([1, 2])
tensor([[1.4000, 3.2000]])


브로드캐스팅

A : (3, 3, 2)  
B : (2, 3)  

A @ B 연산시에  
A : (3, 3, 2)  
B : (1, 2, 3) => (3, 2, 3)  

=> (3, 3, 3)

브로드캐스팅 (Batch가 이미 1이 아니거나 존재하는 경우)  
A : (3, 3, 2)  
B : (4, 2, 3)

=> batch 차원이 3과 4로 달라 계산되지 않음

In [17]:
x = torch.randn(2, 3, 2)
W = torch.randn(2, 4, 2)

y = x @ W.transpose(1, 2)
y.size()


torch.Size([2, 3, 4])

W.transpose(1, 2) : (2, 4, 2) 차원끼리 치환  
(2, 3, 2) @ (2, 2, 4) => (2, 3, 4)  

이미지 계열 조작할때 주로 사용

4. 간단한 선형 연산 구현

In [19]:
import torch
import torch.nn as nn

X = torch.FloatTensor([[1.0, 2.0, 3.0]]) # (1, 3)
W = torch.FloatTensor([[0.1, 0.2, 0.3], [0.4, 0.5, 0.6]]) # (2, 3)


print(X.size(), W.size())

torch.Size([1, 3]) torch.Size([2, 3])


In [21]:
# 편향 계산이 제거된 선형 모델
linear = nn.Linear(
    in_features = 3,  # 입력 벡터의 길이(열 수)
    out_features = 2, # 출력 벡터의 길이(행 수)
    bias=False
)

In [22]:

with torch.no_grad():
    linear.weight.copy_(W) # 가중치 W값으로 모델 가중치 초기화(주입)

In [23]:
y2 = linear(X)
y2

tensor([[1.4000, 3.2000]], grad_fn=<MmBackward0>)

X = (1, 3)
W = (2, 3)
