In [3]:
import numpy as np

In [4]:
def identity_function(x):
    return x

x = np.array([1.0, 2.0, 3.0])
print(identity_function(x))

[1. 2. 3.]


In [5]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

x = np.array([0.0, 2.0, -1.0])
print(sigmoid(x))

[0.5        0.88079708 0.26894142]


Sigmoid 함수로 나온 예측확률을 임계값을 기준으로 예측 결과로서 결정
출력값 >= 0.5 -> 클래스 1
출력값 < 0.5 -> 클래스 0

In [6]:
def softmax(x):
    exp_x = np.exp(x)
    return exp_x / np.sum(exp_x)

x = np.array([2.0, 1.0, 0.1])
print(softmax(x))


[0.65900114 0.24243297 0.09856589]


In [ ]:
def stable_softmax(x):
    x_max = np.max(x)
    exp_x = np.exp(x - x_max)  # 최대값을 빼서 안정적으로 변환
    return exp_x / np.sum(exp_x)

x = np.array([1000, 1001, 1002])  # 큰 값에서도 안정적으로 동작
print(stable_softmax(x))