In [2]:
import torch

In [3]:
a = torch.FloatTensor([[1,2], [3,4]]) # 2차원
b = torch.FloatTensor([[1,2], [1,2]]) # 2차원

c = torch.matmul(a, b) # 행렬 곱
c

tensor([[ 3.,  6.],
        [ 7., 14.]])

In [4]:
d = a@b # 행렬곱
d

tensor([[ 3.,  6.],
        [ 7., 14.]])

1D X 1D => 내적 (np.dot)  
2D X 2D => 행렬 곱  
고차원 => 배치 행렬 곱  

In [5]:
c = torch.IntTensor([[1,2], [3,4]])
c

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

IntTensor도 선언 가능하지만 일반적으로 딥러닝에서 가중치, 출력값, 손실, 기울기 등 모든 연산

In [6]:
c = torch.ByteTensor([[1,2], [3,4]])
c

tensor([[1, 2],
        [3, 4]], dtype=torch.uint8)

In [7]:
mask = torch.BoolTensor([True, False, True])

mask

tensor([ True, False,  True])

In [8]:
x = torch.FloatTensor(3,2) # shape = (3,2)인 텐서
x

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [9]:
a = torch.zeros(3,2)
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [10]:
b = torch.ones(3,2)
b

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [11]:
c = torch.randn(3,2) # 정규 분포 난수
c

tensor([[1.5668, 2.1533],
        [0.5738, 0.4186],
        [1.5668, 1.8163]])

In [12]:
import numpy as np
x = np.array([[1,2],[3,4]])

print(x,type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [13]:
# Pytorch tensor로 변환
x = torch.from_numpy(x)
x.long()

tensor([[1, 2],
        [3, 4]])

In [14]:

print(x,type(x))

tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>


In [15]:
x = x.numpy()
print(x,type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [16]:
x.float()
print(x,type(x))

AttributeError: 'numpy.ndarray' object has no attribute 'float'

In [ ]:
torch.FloatTensor([1,0]).bool() # BoolTensor 형태 변환

tensor([ True, False])

In [ ]:
x = torch.FloatTensor([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]]) # 3차원

print(x.size()) # Pytorch 메서드
print(x.shape) # numpy 스타일

torch.Size([3, 2, 2])
torch.Size([3, 2, 2])


In [ ]:
print(x.dim()) # 텐서의 차원 수 (3,2,2) -> 3 차원

3


In [ ]:
print(len(x.size())) # 텐서의 길이 -> 차원 수

3


In [ ]:
# 텐서의 특정 차원에 있는 요소의 개수
print(x.size(1)) # Pytorch 메서드 (1번 축 크기)
print(x.shape[1]) # Numpy 스타일 (1번 축 크기)

2
2


In [ ]:
# 마지막 차원 요소 개수
print(x.size(-1)) # Pytorch 메서드 (1번 축 크기)
print(x.shape[-1]) # Numpy 스타일 (1번 축 크기)

2
2


In [ ]:
import torch
a = torch.FloatTensor([[1,2], [3,4]]) # 2차원
b = torch.FloatTensor([[1,2], [1,2]]) # 2차원


In [ ]:
a + b

tensor([[2., 4.],
        [4., 6.]])

In [ ]:
a - b

tensor([[0., 0.],
        [2., 2.]])

In [ ]:
a * b

tensor([[1., 4.],
        [3., 8.]])

In [ ]:
a / b

tensor([[1., 1.],
        [3., 2.]])

In [ ]:
a % b

tensor([[0., 0.],
        [0., 0.]])

In [ ]:
a == b

tensor([[ True,  True],
        [False, False]])

In [ ]:
a != b

tensor([[False, False],
        [ True,  True]])

In [ ]:
a ** b

tensor([[ 1.,  4.],
        [ 3., 16.]])

In [ ]:
print(a)
print(b)

tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [1., 2.]])


In [ ]:
print(a.mul_(b)) # _가 붙은 연산은 원본 Tensor를 바꿔주는 in-place 역할을 한다.

tensor([[1., 4.],
        [3., 8.]])


In [ ]:
print(a)

tensor([[1., 4.],
        [3., 8.]])


In [ ]:
print(a.sum()) # 전체 합
print(a.mean()) # 전체 평균

tensor(16.)
tensor(4.)


In [ ]:
print(a.sum(dim=0)) # 행 축을 따라 값들을 더함 (행 축은 사라진다)
print(a.sum(dim=1)) # 열 축을 따라 값들을 더함 (열 축은 사라진다)

tensor([ 4., 12.])
tensor([ 5., 11.])


해당 dim 차원을 합치기 때문에 해당 축은 사라진다

In [ ]:
a.sum(dim=1).shape

torch.Size([2])

Broadcast : 텐서의 차원(크기)이 다를 때, 자동으로 차원을 확장해 차원을 맞춰주는 기능

In [ ]:
x = torch.FloatTensor([[1,2]])
y = torch.FloatTensor([[4,8]])
print(x.shape)
print(y.shape)

torch.Size([1, 2])
torch.Size([1, 2])


In [ ]:
z = x + y
print(z, z.size())

tensor([[ 5., 10.]]) torch.Size([1, 2])


In [ ]:
x = torch.FloatTensor([[1,2],[3,4]])

y = 1

print(x.shape)

torch.Size([2, 2])


In [ ]:
z = x+y
print(z,z.shape)

tensor([[2., 3.],
        [4., 5.]]) torch.Size([2, 2])


1 -> [[1,1],[1,1]]  
x와 동일한 shape으로 브로드캐스팅(자동 형변환)

In [ ]:
x = torch.FloatTensor([[1,2],[3,4]])
y = torch.FloatTensor([1,2])
print(x.shape,y.shape)

torch.Size([2, 2]) torch.Size([2])


In [ ]:
z = x+y
print(z, z.size())

tensor([[2., 4.],
        [4., 6.]]) torch.Size([2, 2])


[3,5] -> [[3,5],[3,5]]  
x의 행 수 만큼 복제

In [ ]:
x = torch.FloatTensor([[[1,2]]])
y = torch.FloatTensor([1,2])
print(x.shape,y.shape)

torch.Size([1, 1, 2]) torch.Size([2])


마지막 차원수 2로 같기 때문에 나머지 차원은 y에 없으므로 자동으로 1로 확장

In [ ]:
z = x+y
print(z,z.size())

tensor([[[2., 4.]]]) torch.Size([1, 1, 2])


In [ ]:
x = torch.FloatTensor([[1,2]])
y = torch.FloatTensor([[3],[5]])
print(x.shape,y.shape)

torch.Size([1, 2]) torch.Size([2, 1])


In [ ]:
z = x+y
print(z,z.size())

tensor([[4., 5.],
        [6., 7.]]) torch.Size([2, 2])


개수가 1인 차원은 확장된다.  
마지막 차원 2 와 1 -> 1이 확장되어 2  
앞 차원 1 과 2 -> 1이 확장되어 2  
=> 2,2  
[[1,2]] => [[1,2],[1,2]]  
[[3],[5]] => [[3,3],[5,5]]

In [ ]:
x = torch.FloatTensor([[1,2],[3,4]])
y = torch.FloatTensor([[1,2,3],[4,5,6],[7,8,9]])
print(x.shape,y.shape)

torch.Size([3, 2]) torch.Size([3, 3])


In [ ]:
z = x+y

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1

0번 차원 : x는 1, y는 - => 자동 확장 가능  
1번 차원 : y는 2, y는 3 => 다른데, 하나라도 1이면 가능하지만 둘다 1이 아님  
2번 차원 : y는 2, y는 3 => 다른데, 하나라도 1이면 가능하지만 둘다 1이 아님  
브로드캐스팅 조건 : 각 차원의 값이 같거나, 하나가 1일 경우에만 자동 확장 가능

In [ ]:
x = torch.FloatTensor([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])

In [ ]:
print(x.reshape(12)) # shape을 명시적으로 지정 (12개 요소를 가진 1차원 텐서)
print(x.reshape(-1)) # -1 : 자동 지정 (자동 지정되는 개수의 요소를 가진 1차원 텐서)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])


In [ ]:
print(x.reshape(3,4)) # 3행 4열로 shape 재구성
print(x.reshape(3,-1)) # 동일

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [ ]:
print(x.reshape(3,2,2,1))

tensor([[[[ 1.],
          [ 2.]],

         [[ 3.],
          [ 4.]]],


        [[[ 5.],
          [ 6.]],

         [[ 7.],
          [ 8.]]],


        [[[ 9.],
          [10.]],

         [[11.],
          [12.]]]])


In [ ]:
print(x.view(3,2,2,1))

tensor([[[[ 1.],
          [ 2.]],

         [[ 3.],
          [ 4.]]],


        [[[ 5.],
          [ 6.]],

         [[ 7.],
          [ 8.]]],


        [[[ 9.],
          [10.]],

         [[11.],
          [12.]]]])


view() : 연속된 데이터 구조일때 사용  
reshape() : 필요시 데이터복사도 가능한 유연한 재구성 함수  

In [ ]:
# squeeze() : 텐서에서 크기가 1인 차원 제거
x = torch.FloatTensor([[[1,2],[3,4]]])
print(x.shape)

torch.Size([1, 2, 2])


In [ ]:
print(x.squeeze(),x.squeeze().size())

tensor([[1., 2.],
        [3., 4.]]) torch.Size([2, 2])


In [ ]:
# unsqueeze() : 텐서에서 크기가 1인 차원 제거
x = torch.FloatTensor([[1,2],[3,4]])
print(x.shape)

torch.Size([2, 2])


In [ ]:
print(x.unsqueeze(2), x.unsqueeze(2).size())   # 2번 차원
print(x.unsqueeze(-1), x.unsqueeze(-1).size()) # 마지막 차원
print(x.reshape(2,2,-1), x.reshape(2,2,-1).shape) 

tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]]) torch.Size([2, 2, 1])
tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]]) torch.Size([2, 2, 1])
tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]]) torch.Size([2, 2, 1])


차원 조작같은 경우 입력층 -> 은닉층 또는 은닉층 -> 출력층 부분에서  
차원을 맞춰서 값을 넘겨야할 때 주로 사용한다.

텐서를 자르고 붙이기 (Indexing & Slicing)

In [ ]:
x = torch.FloatTensor([[[1, 2],
                        [3, 4]],
                       [[5, 6],
                        [7, 8]],
                       [[9, 10],
                        [11, 12]]]) # 3차원 

x.size()

torch.Size([3, 2, 2])

In [22]:
print(x[0])  # 첫 번째 차원(dim=0)에서 인덱스 0 선택
print(x[0, :, :])  # 생략된 차원을 명시적으로 표시

tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [3., 4.]])


In [23]:
print(x[0, :])  # 첫 번째 차원 (dim=0)에서 두 번째 차원(dim=1)을 :(전체) 선택

tensor([[1., 2.],
        [3., 4.]])


뒤쪽 차원의 : (전체선택)은 생략 가능하며, 생략하면 자동으로 : (전체선택) 처리된다.

In [33]:
print(x[-1])
print(x[-1, :])
print(x[-1, :, :])

tensor([[ 9., 10.],
        [11., 12.]])
tensor([[ 9., 10.],
        [11., 12.]])
tensor([[ 9., 10.],
        [11., 12.]])


In [25]:
print(x[:, 0, :],x[:, 0, :].size()) # 전체 배치에서 첫번째 행만 가져옴 (열 전체)

tensor([[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]]) torch.Size([3, 2])


배치는 그대로 3 유지  
행은 선택되어 제거  
열은 그대로 2 유지

In [27]:
# 슬라이싱으로 접근시 차원 수 유지
print(x[1:3, :, :], x[1:3, :, :].size())


tensor([[[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]]) torch.Size([2, 2, 2])


In [ ]:
print(x[:, :1, :], x[:, :1, :].size()) # 모든 배치. 행은 앞의 1개만 슬라이싱

tensor([[[ 1.,  2.]],

        [[ 5.,  6.]],

        [[ 9., 10.]]]) torch.Size([3, 1, 2])


In [41]:
print(x[:, :-1, :],x[:, :-1, :].size()) # 모든 배치. 행은 마지막 행 제외, 열은 전체

tensor([[[ 1.,  2.]],

        [[ 5.,  6.]],

        [[ 9., 10.]]]) torch.Size([3, 1, 2])


In [74]:
# split() : 텐서를 원하는 모양으로 나눠준다. (앞에서부터 split)
x = torch.zeros(10,4)
x

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [78]:
splits = x.split(4,dim=0)
print(splits)

(tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]), tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]), tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]]))


In [77]:
for split in splits:
    print(split)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [82]:
# chunk() : 텐서를 청크 수로 나눈다 (나누기방식과 비슷 (균등하게))
x = torch.zeros(8,4)
chunks = x.chunk(4,dim=0)
for chunk in chunks:
    print(chunk)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])


split(n,dim) : n개로 균등하게 분할 (크기)  
chunk(size,dim) : size만큼 조각하여 자른다 (개수)  
split : 4 -> 4,4,2  
chunk : 4 -> 2,2,2,2  

In [88]:
# index_select() : 차원
x = torch.IntTensor([[[1, 2],
                        [3, 4]],
                       [[5, 6],
                        [7, 8]],
                       [[9, 10],
                        [11, 12]]])

indice = torch.LongTensor([2,1])
x.size()

torch.Size([3, 2, 2])

In [ ]:
# 0번 차원 indice에서 지정한 순서대로 선택
# [2, 1] -> x[2], 그 다음 x[1]
y = x.index_select(dim=0, index=indice) 

y

tensor([[[ 9, 10],
         [11, 12]],

        [[ 5,  6],
         [ 7,  8]]], dtype=torch.int32)

index_select 함수는 반환값이 있어 텐서가 새로 생성되어 사용시 값으로 받아준다.  
index는 LongTensor형태로 전달해준다.

In [95]:
x.index_select(0,index=torch.LongTensor([0,0])) # 인덱스 중복 선택 x[0],x[0]

tensor([[[1, 2],
         [3, 4]],

        [[1, 2],
         [3, 4]]], dtype=torch.int32)

In [119]:
# cat() : 여러 텐서간에 연결
x = torch.IntTensor([[1,2,3],[4,5,6],[7,8,9]])
y = torch.IntTensor([[10,11,12],[13,14,15],[16,17,18]])

print(x.size(),y.size())

torch.Size([3, 3]) torch.Size([3, 3])


In [136]:
z = torch.cat([x,y],dim=0) # 0번 차원 (행 방향)으로 이어 붙임
print(z,"\n",z.size())


tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]], dtype=torch.int32) 
 torch.Size([6, 3])


cat()으로 붙이는 축을 제외한 나머지 차원은 반드시 동일해야 이어 붙일 수 있다.  
2차원 Tensor 기준 dim = 0 : 행 증가  
2차원 Tensor 기준 dim = 1 : 열 증가  

In [ ]:
z = torch.cat([x,y],dim=1) #(3,6)
print(z,"\n",z.size())

tensor([[ 1,  2,  3, 10, 11, 12,  1,  2,  3],
        [ 4,  5,  6, 13, 14, 15,  4,  5,  6],
        [ 7,  8,  9, 16, 17, 18,  7,  8,  9]], dtype=torch.int32) 
 torch.Size([3, 9])


In [ ]:
# stack() : 여러 텐서를 쌓아 새로운 차원을 만든다
z = torch.stack([x,y]) # x, y 2차원 데이터를 2장 쌓아 (2,3,3) 형태로 만든다
print(z,"\n",z.size())

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]], dtype=torch.int32) /n torch.Size([2, 3, 3])


cat() : 차원 수 동일. 기존 축에 그대로 이어 붙임  
stack() : 차원 수 + 1. 새로운 축을 만들어 쌓음  

In [148]:
print(torch.cat([x,y]).size())
print(torch.stack([x,y]).size())

torch.Size([6, 3])
torch.Size([2, 3, 3])


In [163]:
z = torch.stack([x,y],dim=1)
print(z,"\n",z.size())

tensor([[[ 1,  2,  3],
         [10, 11, 12]],

        [[ 4,  5,  6],
         [13, 14, 15]],

        [[ 7,  8,  9],
         [16, 17, 18]]], dtype=torch.int32) 
 torch.Size([3, 2, 3])


In [162]:
z = torch.stack([x,y],dim=-1) # 마지막 차원 추가 (feature, channel 차원)
print(z,"\n",z.size())

tensor([[[ 1, 10],
         [ 2, 11],
         [ 3, 12]],

        [[ 4, 13],
         [ 5, 14],
         [ 6, 15]],

        [[ 7, 16],
         [ 8, 17],
         [ 9, 18]]], dtype=torch.int32) 
 torch.Size([3, 3, 2])


In [167]:
# cat 과 unsqueeze() 사용하여 stack 구현하기
z = torch.cat([x.unsqueeze(0),y.unsqueeze(0)],dim=0)
z

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]], dtype=torch.int32)

In [ ]:
# 반복문 결과를 하나로 병합해보기 (2,2) -> (5,2,2) 배치 데이터 생성시 사용
result = []
for i in range(5):
    x = torch.IntTensor(2,2)
    result += [x] # 텐서를 리스트에 하나씩 추가
result = torch.stack(result) # 리스트 텐서들을 새로운 차원으로 쌓음
result.size()


tensor([[[         0, 2146435072],
         [         0,  926341120]],

        [[         0,          0],
         [         0,          0]],

        [[         0,          0],
         [         0,          0]],

        [[         0,          0],
         [         0,          0]],

        [[         2,          0],
         [         1,          0]]], dtype=torch.int32)

# Pytorch 메서드

In [172]:
# expand() : 크기가 1인 차원을 지정된 크기만큼 확장. 같은 값이 반복된 것처럼 보이게 해준다.
x = torch.IntTensor([[[1,2]],[[3,4]]])
print(x.shape)

torch.Size([2, 1, 2])


In [183]:
y = x.expand(*[2,4,2]) # 기존 (2, 1, 2) 에서 행 차원을 1 -> 4
y

tensor([[[1, 2],
         [1, 2],
         [1, 2],
         [1, 2]],

        [[3, 4],
         [3, 4],
         [3, 4],
         [3, 4]]], dtype=torch.int32)

In [184]:
y = x.expand(2,4,2) # 기존 (2, 1, 2) 에서 행 차원을 1 -> 4
y

tensor([[[1, 2],
         [1, 2],
         [1, 2],
         [1, 2]],

        [[3, 4],
         [3, 4],
         [3, 4],
         [3, 4]]], dtype=torch.int32)

expand()는 값을 복사하지는 않는다. 내부적으로 같은 메모리를 여러 번 참조해서 사용
- 메모리 효율성이 높다.

값 앞에 * 는 unpacking 은 list나 tuple형 데이터를 순차적으로 전달


In [187]:
# cat을 활용하여 expand 처럼 구현하기
y = torch.cat([x,x,x],dim=1) # dim=1 (두번째 차원) 기준으로 x를 3번 이어붙임

print(y,"\n",y.size())

tensor([[[1, 2],
         [1, 2],
         [1, 2]],

        [[3, 4],
         [3, 4],
         [3, 4]]], dtype=torch.int32) 
 torch.Size([2, 3, 2])


In [ ]:
# randperm(n) : 랜덤 수열. 0부터 n-1까지의 정수를 무작위로 섞은 순열 텐서를 반환
# (특징 : 중복없음)
x = torch.randperm(10)
print(x,"\n",x.size())

tensor([1, 6, 8, 3, 0, 7, 4, 2, 9, 5]) 
 torch.Size([10])


In [194]:
x = torch.randperm(3**3).reshape(3,3,-1) # 0~26 27개 값. 3차원으로 재구성
print(x,"\n",x.size())

tensor([[[11, 13, 16],
         [26, 24,  9],
         [25,  1, 15]],

        [[18, 10,  8],
         [ 6, 23, 17],
         [20,  3,  5]],

        [[22,  0, 14],
         [19,  7,  4],
         [21,  2, 12]]]) 
 torch.Size([3, 3, 3])


In [201]:
# argmax() : 최대값 인덱스 반환
idx = x.argmax(dim=-1) # 마지막 차원(열)에서 가장 큰 값의 인덱스를 반환하고, 그 차원은 제거
print(idx,"\n",idx.size())

tensor([[2, 0, 0],
        [0, 1, 0],
        [0, 0, 0]]) 
 torch.Size([3, 3])


argmax(dim=k) : k번 차원에서 가장 큰 값의 인덱스를 선택하고, 그 차원 제거

In [202]:
idx = x.argmax(dim=-1,keepdim=True) # 마지막 차원(열)에서 가장 큰 값의 인덱스를 반환하고, 차원 유지
print(idx,"\n",idx.size())

tensor([[[2],
         [0],
         [0]],

        [[0],
         [1],
         [0]],

        [[0],
         [0],
         [0]]]) 
 torch.Size([3, 3, 1])


In [206]:
# topk() : 상위 k개의 값과 해당 인덱스를 튜플로 반환
values, indices = torch.topk(x,k=1,dim=-1)

print(values,"\n",values.size())
print(indices,"\n",indices.size())

tensor([[[16],
         [26],
         [25]],

        [[18],
         [23],
         [20]],

        [[22],
         [19],
         [21]]]) 
 torch.Size([3, 3, 1])
tensor([[[2],
         [0],
         [0]],

        [[0],
         [1],
         [0]],

        [[0],
         [0],
         [0]]]) 
 torch.Size([3, 3, 1])


topk(k=1)로 설정하면 argmax(keepdim=True)와 같은 결과  

In [ ]:
# topk를 이용해 정렬하기
target_dim = -1
values,indices = torch.topk(
    x,
    k=x.size(target_dim), # 마지막 차원의 전체 길이
    largest=True          # 큰 값부터 선택
)
print(x,"\n",values) # 정렬된 값
print(indices,"\n") # 정렬된 index

tensor([[[11, 13, 16],
         [26, 24,  9],
         [25,  1, 15]],

        [[18, 10,  8],
         [ 6, 23, 17],
         [20,  3,  5]],

        [[22,  0, 14],
         [19,  7,  4],
         [21,  2, 12]]]) 
 tensor([[[16, 13, 11],
         [26, 24,  9],
         [25, 15,  1]],

        [[18, 10,  8],
         [23, 17,  6],
         [20,  5,  3]],

        [[22, 14,  0],
         [19,  7,  4],
         [21, 12,  2]]])
tensor([[[2, 1, 0],
         [0, 1, 2],
         [0, 2, 1]],

        [[0, 1, 2],
         [1, 2, 0],
         [0, 2, 1]],

        [[0, 2, 1],
         [0, 1, 2],
         [0, 2, 1]]]) 



x[i, j, :]을 큰 값 기준으로 내림차순 정렬  
- 차원 수는 그대로 유지. 값의 순서만 바뀜
- 각 줄에서 큰 값 -> 작은 값 순 정렬

indices는 정렬되기 전 위치값

결과적으로 topk(k=차원 크기)를 주면 해당 차원을 기준으로 값을 정렬한 효과를 얻는다.

In [225]:
k = 1
values, indices = torch.sort(x, dim=1, descending=True) # 마지막 차원을 기준으로 내림차순 정렬 (값, 원래위치)

values,indices = values[:, :, :k],indices[:, :, :k] # 정렬된 결과 중 가장 큰 값 1개 선택(3,3,1)
print(values.squeeze(-1), values.squeeze(-1).size(), "\n") # (3, 3, 1) -> (3,3)
print(indices.squeeze(-1), indices.squeeze(-1).size()) # (3, 3, 1) -> (3,3)



tensor([[26, 25, 11],
        [20, 18,  6],
        [22, 21, 19]]) torch.Size([3, 3]) 

tensor([[1, 2, 0],
        [2, 0, 1],
        [0, 2, 1]]) torch.Size([3, 3])


sort + 슬라이싱 = topk 사용과 동일한 효과를 얻는다.

In [ ]:
# masked_fill() : 마스크가 True인 위치에 지정된 값을 채움
x = torch.IntTensor([i for i in range(3**2)]).reshape(3,-1) # -1 -> 3
x

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]], dtype=torch.int32)

In [ ]:
# x = torch.IntTensor([i for i in range(3**2)]).reshape(1,1,-1) # -1 -> 9
# x

In [245]:
mask = x > 4
mask

tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])

In [246]:
y = x.masked_fill(mask,value=-1)

print(y)

tensor([[ 0,  1,  2],
        [ 3,  4, -1],
        [-1, -1, -1]], dtype=torch.int32)


사용처
- 이미지 처리 padding 처리
- loss 계산에서 해당 값 무시

In [250]:
# ones(), zeros() : 모든 요소가 0, 1로 채워진 텐서 반환
torch.set_printoptions(sci_mode=False)
print(torch.ones(2,3))
print(torch.zeros(2,3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [253]:
print(x.size(),y.size())

torch.Size([3, 3]) torch.Size([3, 3])


In [251]:
# ones_like(), zeros_like() : 기준 텐서와 동일한 형태의 초기화 텐서 반환
print(torch.ones_like(x))
print(torch.zeros_like(y))


tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)
