In [2]:
import torch

In [ ]:
a = torch.FloatTensor([[1,2], [3,4]]) # 2차원
b = torch.FloatTensor([[1,2], [1,2]]) # 2차원

c = torch.matmul(a, b) # 행렬 곱
c

tensor([[ 3.,  6.],
        [ 7., 14.]])

In [ ]:
d = a@b # 행렬곱
d

tensor([[ 3.,  6.],
        [ 7., 14.]])

1D X 1D => 내적 (np.dot)  
2D X 2D => 행렬 곱  
고차원 => 배치 행렬 곱  

In [7]:
c = torch.IntTensor([[1,2], [3,4]])
c

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

IntTensor도 선언 가능하지만 일반적으로 딥러닝에서 가중치, 출력값, 손실, 기울기 등 모든 연산

In [6]:
c = torch.ByteTensor([[1,2], [3,4]])
c

tensor([[1, 2],
        [3, 4]], dtype=torch.uint8)

In [9]:
mask = torch.BoolTensor([True, False, True])

mask

tensor([ True, False,  True])

In [13]:
x = torch.FloatTensor(3,2) # shape = (3,2)인 텐서
x

tensor([[-1.5283e-36,  1.2430e-42],
        [ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00]])

In [15]:
a = torch.zeros(3,2)
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [17]:
b = torch.ones(3,2)
b

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [21]:
c = torch.randn(3,2) # 정규 분포 난수
c

tensor([[ 0.5822, -0.6621],
        [-0.9741,  0.0708],
        [ 0.0435,  0.3771]])

In [41]:
import numpy as np
x = np.array([[1,2],[3,4]])

print(x,type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [ ]:
# Pytorch tensor로 변환
x = torch.from_numpy(x)
x.long()

In [43]:

print(x,type(x))

tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>


In [30]:
x = x.numpy()
print(x,type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [44]:
x.float()
print(x,type(x))

tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>


In [45]:
torch.FloatTensor([1,0]).bool() # BoolTensor 형태 변환

tensor([ True, False])

In [49]:
x = torch.FloatTensor([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]]) # 3차원

print(x.size()) # Pytorch 메서드
print(x.shape) # numpy 스타일

torch.Size([3, 2, 2])
torch.Size([3, 2, 2])


In [50]:
print(x.dim()) # 텐서의 차원 수 (3,2,2) -> 3 차원

3


In [51]:
print(len(x.size())) # 텐서의 길이 -> 차원 수

3


In [ ]:
# 텐서의 특정 차원에 있는 요소의 개수
print(x.size(1)) # Pytorch 메서드 (1번 축 크기)
print(x.shape[1]) # Numpy 스타일 (1번 축 크기)

2
2


In [54]:
# 마지막 차원 요소 개수
print(x.size(-1)) # Pytorch 메서드 (1번 축 크기)
print(x.shape[-1]) # Numpy 스타일 (1번 축 크기)

2
2


In [ ]:
import torch
a = torch.FloatTensor([[1,2], [3,4]]) # 2차원
b = torch.FloatTensor([[1,2], [1,2]]) # 2차원


In [56]:
a + b

tensor([[2., 4.],
        [4., 6.]])

In [57]:
a - b

tensor([[0., 0.],
        [2., 2.]])

In [58]:
a * b

tensor([[1., 4.],
        [3., 8.]])

In [59]:
a / b

tensor([[1., 1.],
        [3., 2.]])

In [65]:
a % b

tensor([[0., 0.],
        [0., 0.]])

In [66]:
a == b

tensor([[ True,  True],
        [False, False]])

In [67]:
a != b

tensor([[False, False],
        [ True,  True]])

In [68]:
a ** b

tensor([[ 1.,  4.],
        [ 3., 16.]])

In [70]:
print(a)
print(b)

tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [1., 2.]])


In [71]:
print(a.mul_(b)) # _가 붙은 연산은 원본 Tensor를 바꿔주는 in-place 역할을 한다.

tensor([[1., 4.],
        [3., 8.]])


In [72]:
print(a)

tensor([[1., 4.],
        [3., 8.]])


In [73]:
print(a.sum()) # 전체 합
print(a.mean()) # 전체 평균

tensor(16.)
tensor(4.)


In [74]:
print(a.sum(dim=0)) # 행 축을 따라 값들을 더함 (행 축은 사라진다)
print(a.sum(dim=1)) # 열 축을 따라 값들을 더함 (열 축은 사라진다)

tensor([ 4., 12.])
tensor([ 5., 11.])


해당 dim 차원을 합치기 때문에 해당 축은 사라진다

In [75]:
a.sum(dim=1).shape

torch.Size([2])

Broadcast : 텐서의 차원(크기)이 다를 때, 자동으로 차원을 확장해 차원을 맞춰주는 기능

In [77]:
x = torch.FloatTensor([[1,2]])
y = torch.FloatTensor([[4,8]])
print(x.shape)
print(y.shape)

torch.Size([1, 2])
torch.Size([1, 2])


In [79]:
z = x + y
print(z, z.size())

tensor([[ 5., 10.]]) torch.Size([1, 2])


In [80]:
x = torch.FloatTensor([[1,2],[3,4]])

y = 1

print(x.shape)

torch.Size([2, 2])


In [81]:
z = x+y
print(z,z.shape)

tensor([[2., 3.],
        [4., 5.]]) torch.Size([2, 2])


1 -> [[1,1],[1,1]]  
x와 동일한 shape으로 브로드캐스팅(자동 형변환)

In [82]:
x = torch.FloatTensor([[1,2],[3,4]])
y = torch.FloatTensor([1,2])
print(x.shape,y.shape)

torch.Size([2, 2]) torch.Size([2])


In [83]:
z = x+y
print(z, z.size())

tensor([[2., 4.],
        [4., 6.]]) torch.Size([2, 2])


[3,5] -> [[3,5],[3,5]]  
x의 행 수 만큼 복제

In [84]:
x = torch.FloatTensor([[[1,2]]])
y = torch.FloatTensor([1,2])
print(x.shape,y.shape)

torch.Size([1, 1, 2]) torch.Size([2])


마지막 차원수 2로 같기 때문에 나머지 차원은 y에 없으므로 자동으로 1로 확장

In [85]:
z = x+y
print(z,z.size())

tensor([[[2., 4.]]]) torch.Size([1, 1, 2])


In [88]:
x = torch.FloatTensor([[1,2]])
y = torch.FloatTensor([[3],[5]])
print(x.shape,y.shape)

torch.Size([1, 2]) torch.Size([2, 1])


In [89]:
z = x+y
print(z,z.size())

tensor([[4., 5.],
        [6., 7.]]) torch.Size([2, 2])


개수가 1인 차원은 확장된다.  
마지막 차원 2 와 1 -> 1이 확장되어 2  
앞 차원 1 과 2 -> 1이 확장되어 2  
=> 2,2  
[[1,2]] => [[1,2],[1,2]]  
[[3],[5]] => [[3,3],[5,5]]

In [ ]:
x = torch.FloatTensor([[1,2],[3,4]])
y = torch.FloatTensor([[1,2,3],[4,5,6],[7,8,9]])
print(x.shape,y.shape)

torch.Size([3, 2]) torch.Size([3, 3])


In [94]:
z = x+y

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1

0번 차원 : x는 1, y는 - => 자동 확장 가능  
1번 차원 : y는 2, y는 3 => 다른데, 하나라도 1이면 가능하지만 둘다 1이 아님  
2번 차원 : y는 2, y는 3 => 다른데, 하나라도 1이면 가능하지만 둘다 1이 아님  
브로드캐스팅 조건 : 각 차원의 값이 같거나, 하나가 1일 경우에만 자동 확장 가능

In [96]:
x = torch.FloatTensor([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])

In [ ]:
print(x.reshape(12)) # shape을 명시적으로 지정 (12개 요소를 가진 1차원 텐서)
print(x.reshape(-1)) # -1 : 자동 지정 (자동 지정되는 개수의 요소를 가진 1차원 텐서)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])


In [ ]:
print(x.reshape(3,4)) # 3행 4열로 shape 재구성
print(x.reshape(3,-1)) # 동일

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [99]:
print(x.reshape(3,2,2,1))

tensor([[[[ 1.],
          [ 2.]],

         [[ 3.],
          [ 4.]]],


        [[[ 5.],
          [ 6.]],

         [[ 7.],
          [ 8.]]],


        [[[ 9.],
          [10.]],

         [[11.],
          [12.]]]])


In [ ]:
print(x.view(3,2,2,1))

tensor([[[[ 1.],
          [ 2.]],

         [[ 3.],
          [ 4.]]],


        [[[ 5.],
          [ 6.]],

         [[ 7.],
          [ 8.]]],


        [[[ 9.],
          [10.]],

         [[11.],
          [12.]]]])


view() : 연속된 데이터 구조일때 사용  
reshape() : 필요시 데이터복사도 가능한 유연한 재구성 함수  

In [101]:
# squeeze() : 텐서에서 크기가 1인 차원 제거
x = torch.FloatTensor([[[1,2],[3,4]]])
print(x.shape)

torch.Size([1, 2, 2])


In [102]:
print(x.squeeze(),x.squeeze().size())

tensor([[1., 2.],
        [3., 4.]]) torch.Size([2, 2])


In [105]:
# unsqueeze() : 텐서에서 크기가 1인 차원 제거
x = torch.FloatTensor([[1,2],[3,4]])
print(x.shape)

torch.Size([2, 2])


In [108]:
print(x.unsqueeze(2), x.unsqueeze(2).size())   # 2번 차원
print(x.unsqueeze(-1), x.unsqueeze(-1).size()) # 마지막 차원
print(x.reshape(2,2,-1), x.reshape(2,2,-1).shape) 

tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]]) torch.Size([2, 2, 1])
tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]]) torch.Size([2, 2, 1])
tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]]) torch.Size([2, 2, 1])


차원 조작같은 경우 입력층 -> 은닉층 또는 은닉층 -> 출력층 부분에서  
차원을 맞춰서 값을 넘겨야할 때 주로 사용한다.

텐서를 자르고 붙이기 (Indexing & Slicing)

In [112]:
x = torch.FloatTensor([[1,2],[3,4]])

In [115]:
print(x[0]) # 첫 번째 차원(dim=0)에서 인덱스 0 선택

tensor([1., 2.])


In [116]:
print(x[0, :]) # 첫 번째 차원 (dim=0)에서 두 번째 차원(dim=1)을 :(전체) 선택

tensor([1., 2.])


뒤쪽 차원의 : (전체선택)은 생략 가능하며, 생략하면 자동으로 : (전체선택) 처리된다.